### ISSUE TITLE
[Feature request] filecreate.go - Provide size in Kb

### ISSUE THREAD

**Issue by wikijm** [alwashali/Detection-Validation#2]
Hi @alwashali 

May I ask you to add to filecreate.go a way to precise the size of the file to create?

I thought of something like that:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func filewrite(fpath string, binPath string, sizeInKB int) {
	if binPath != "" {
		directory := filepath.Dir(binPath)
		fileName := filepath.Base(binPath)

		copyBinaryTo(directory, fileName)

		args := []string{"createfile", "--path", fpath, "--size", fmt.Sprintf("%d", sizeInKB)}
		output := execute(binPath, args)
		fmt.Println(output)
		return
	}

	_, err := os.Stat(fpath)
	if os.IsNotExist(err) {
		dir, file := filepath.Split(fpath)
		fmt.Println(dir, "file:", file)
		if err := os.MkdirAll(dir, 0755); err != nil {
			log.Println(err)
		}

		// Create the file with the specified size in KB
		fileSize := int64(sizeInKB) * 1024 // Convert KB to bytes
		file, err := os.Create(fpath)
		if err != nil {
			log.Println(err)
			return
		}
		defer file.Close()

		if err := file.Truncate(fileSize); err != nil {
			log.Println(err)
		}
	}
}
```

I've added a new parameter sizeInKB int to the filewrite function. If the value of sizeInKB is greater than zero, the function will create a file with the specified size in kilobytes. We can then call the filewrite function, passing the desired size when you use the "createfile" subcommand.

For example:
`mcli.exe createfile --path f.dat --binpath c:\temp\w.exe --size 1024`

Let me know what you think 😄 
Thanks!

Regards,
WikiJM

**Comment by alwashali** [comment]
I have added some content to the file create event which will cause it to have some detection 
I noticed some EDRs ignores the file if it's 0 bytes. 

Now it's better 

I don't think we need to specify the size, just any content
Thanks for your comments though
