### ISSUE TITLE
Super cool idea! Minor issue - dnsquery 'flag provided but not defined'

### ISSUE THREAD

**Issue by mathurin68** [alwashali/Detection-Validation#3]
The 'execute' seems to work...
.\magicbinary.exe execute --parent w3wp.exe --command powershell.exe
![image](https://github.com/alwashali/detection-validation/assets/5932961/488eb74a-c58e-4c72-a768-ee0dcc2d467c)

![image](https://github.com/alwashali/detection-validation/assets/5932961/9515496f-29c0-40cf-a2a1-b3ec99ab8def)

but the dnsquery doesn't seem to want to work when copying the example straight from the page - 
![image](https://github.com/alwashali/detection-validation/assets/5932961/b7012296-263b-4e6f-a6da-ccba63206651)

**Comment by alwashali** [comment]
--binpath doesn't exist with dnsquery 
It's not an issue rather a missing flag, I didn't need it before so not implemented !

**Comment by mathurin68** [comment]
Ah, got it, thanks for the response!
